jobmanager.rpc.address: jobmanager
rest.port: 8081
taskmanager.numberOfTaskSlots: 4
parallelism.default: 2
jobmanager.memory.process.size: 1600m
taskmanager.memory.process.size: 1728m
state.backend.type: hashmap
state.checkpoints.dir: file:///tmp/flink-checkpoints
state.savepoints.dir: file:///tmp/flink-savepoints
execution.checkpointing.interval: 30s
execution.checkpointing.mode: EXACTLY_ONCE
env.java.opts.all: --add-opens=java.base/java.util=ALL-UNNAMED
